[workspace]
resolver = "3"
members = ["fleet", "fleetc", "fleetls", "fleetls-lib"]
default-members = ["fleet", "fleetc", "fleetls", "fleetls-lib"]

[profile.dev]
opt-level = 1 # used to avoid stack overflows in debug builds
