[package]
name = "fleetc"
version = "0.1.0"
edition = "2024"
default-run = "fleetc"

[dependencies]
clap = { version = "4.5.46", features = ["derive"] }
clap-verbosity-flag = "3.0.4"
env_logger = "0.11.8"
fleet = { path = "../fleet" }
