[package]
name = "fleetls"
version = "0.1.0"
edition = "2024"

[dependencies]
fleetls-lib = { path = "../fleetls-lib" }
tokio = { version = "1.44.2", features = ["full"] }
tokio-util = { version = "0.7.15", features = ["compat"] }
