name: Main

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Install rsync 📚 # mainly used for Github Pages, but also for resolving symlinks
        run: |
          sudo apt-get update && sudo apt-get install -y rsync
      - run: |
          nix build .#all
          nix build .#web-demo --out-link web-demo-result-link
          rsync -aL web-demo-result-link/ web-demo-result
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: web-demo-result # The folder the action should deploy.

